config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  get 'tasks', to: 'tasks#index'
  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
  patch 'tasks/:id', to: 'tasks#update'
  delete 'tasks/:id', to: 'tasks#destroy'
  get 'tasks/:id', to: 'tasks#show', as: :task

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:id])
     if @task.save
       redirect_to tasks_path
     else
       render :new
     end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to task_path(@task)
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Éditer tâche</h1>

<%= form_with model: @task, url: task_path(@task), local: true do |form| %>
  <div>
    <%= form.label :title, "Titre" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :details, "Détails" %>
    <%= form.text_area :details %>
  </div>
  <div>
    <%= form.label :completed, "Complétée" %>
    <%= form.check_box :completed %>
  </div>
  <div>
    <%= form.submit "Mettre à jour la tâche" %>
  </div>
<% end %>

<%= link_to 'Retour à la tâche', task_path(@task) %>

app/views/tasks/index.html.erb
<h1>Liste des tâches</h1>

<ul>
  <% @tasks.each do |task| %>
    <li>
      <strong><%= link_to task.title, task_path(task) %></strong><br>
      <%= task.details %><br>
      <% if task.completed %>
        <span style="color: green;">Complétée</span>
      <% else %>
        <span style="color: red;">Non complétée</span>
      <% end %>
      <%= link_to 'Éditer', edit_task_path(task) %> |

    </li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p>
  <strong>Détails:</strong>
  <%= @task.details %>
</p>

<p>
  <strong>Status:</strong>
  <% if @task.completed %>
    <span style="color: green;">Complétée</span>
  <% else %>
    <span style="color: red;">Non complétée</span>
  <% end %>
</p>

<%= link_to 'Retour à la liste', tasks_path %>
<%= link_to 'Éditer', edit_task_path(@task) %>
<%= link_to 'Supprimer', task_path(@task), data: {turbo_method: :delete, turbo_confirm: 'Êtes-vous sûr?'}  %>